"""Add Proverb model

Revision ID: 1233050fe93a
Revises: 6d05c39b56f5
Create Date: 2025-07-04 22:52:19.136623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1233050fe93a'
down_revision = '6d05c39b56f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proverbs',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('yoruba_text', sa.Text(), nullable=False),
    sa.Column('english_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('p_id'),
    sa.UniqueConstraint('yoruba_text', 'english_text', name='unique_proverb_pair')
    )
    with op.batch_alter_table('proverbs', schema=None) as batch_op:
        batch_op.create_index('idx_proverbs_yoruba_text', ['yoruba_text'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('proverbs', schema=None) as batch_op:
        batch_op.drop_index('idx_proverbs_yoruba_text')

    op.drop_table('proverbs')
    # ### end Alembic commands ###
