"""Initial database setup

Revision ID: 46094403aefa
Revises: 
Create Date: 2025-04-20 11:45:59.908618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46094403aefa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missing_translations',
    sa.Column('m_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('source_language', sa.String(length=3), nullable=False),
    sa.Column('target_language', sa.String(length=3), nullable=False),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('m_id'),
    sa.UniqueConstraint('text', 'source_language', 'target_language', name='unique_missing_translation')
    )
    op.create_table('words',
    sa.Column('w_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=3), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('part_of_speech', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('w_id'),
    sa.UniqueConstraint('language', 'word', name='unique_language_word')
    )
    op.create_table('daily_words',
    sa.Column('dw_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('en_word_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['en_word_id'], ['words.w_id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.w_id'], ),
    sa.PrimaryKeyConstraint('dw_id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('translations',
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('source_word_id', sa.Integer(), nullable=False),
    sa.Column('target_word_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_word_id'], ['words.w_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_word_id'], ['words.w_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('t_id'),
    sa.UniqueConstraint('source_word_id', 'target_word_id', name='unique_translation_pair')
    )
    op.create_table('examples',
    sa.Column('e_id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('example_source', sa.Text(), nullable=False),
    sa.Column('example_target', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.t_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('e_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examples')
    op.drop_table('translations')
    op.drop_table('daily_words')
    op.drop_table('words')
    op.drop_table('missing_translations')
    # ### end Alembic commands ###
