"""add indexing

Revision ID: 6d05c39b56f5
Revises: 46094403aefa
Create Date: 2025-04-26 10:18:09.707542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d05c39b56f5'
down_revision = '46094403aefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_words', schema=None) as batch_op:
        batch_op.create_index('idx_daily_words_date', ['date'], unique=False)

    with op.batch_alter_table('missing_translations', schema=None) as batch_op:
        batch_op.create_index('idx_missing_hit_count', ['hit_count'], unique=False, postgresql_ops={'hit_count': 'DESC'})
        batch_op.create_index('idx_missing_text_source_target', ['text', 'source_language', 'target_language'], unique=False)

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.create_index('idx_translations_source_word_id', ['source_word_id'], unique=False)
        batch_op.create_index('idx_translations_target_word_id', ['target_word_id'], unique=False)

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index('idx_words_language', ['language'], unique=False)
        batch_op.create_index('idx_words_language_word', ['language', 'word'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index('idx_words_language_word')
        batch_op.drop_index('idx_words_language')

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_index('idx_translations_target_word_id')
        batch_op.drop_index('idx_translations_source_word_id')

    with op.batch_alter_table('missing_translations', schema=None) as batch_op:
        batch_op.drop_index('idx_missing_text_source_target')
        batch_op.drop_index('idx_missing_hit_count', postgresql_ops={'hit_count': 'DESC'})

    with op.batch_alter_table('daily_words', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_words_date')

    # ### end Alembic commands ###
